import React, { useEffect, useMemo, useState } from 'react';
import api, { apiErrorMessage } from '../services/api';
import { portalService } from '../services/portalService';
import './MinhasTurmas.css';

export default function MinhasTurmas() {
  const [classes, setClasses] = useState([]); const [selected, setSelected] = useState(null); const [attendance, setAttendance] = useState({});
  const [evaluationId, setEvaluationId] = useState(''); const [grades, setGrades] = useState({}); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { portalService.getClasses().then(setClasses).catch((e) => setMessage(apiErrorMessage(e))).finally(() => setLoading(false)); }, []);
  const choose = async (item) => { try { const detail = await portalService.getClassDetails(item.id); setSelected(detail); setAttendance(Object.fromEntries(detail.alunos.map((x) => [x.id, true]))); setEvaluationId(detail.atividades[0]?.id || ''); setGrades({}); } catch (e) { setMessage(apiErrorMessage(e)); } };
  const stats = useMemo(() => {
    if (!selected?.alunos.length) return { average: 0, attendance: 0, risk: 0 };
    const averages = selected.alunos.map((x) => [x.p1, x.p2, x.trabalho].filter((n) => n != null)).map((values) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0);
    return { average: averages.reduce((a, b) => a + b, 0) / averages.length, attendance: Object.values(attendance).filter(Boolean).length / selected.alunos.length * 100, risk: averages.filter((x) => x < 6).length };
  }, [attendance, selected]);
  const saveAttendance = async () => { try { await Promise.all(selected.alunos.map((student) => api.post('/professor/faltas', { idMatricula: student.matriculaId, dataAula: new Date().toISOString(), presente: attendance[student.id], justificativa: attendance[student.id] ? null : 'Ausência sem justificativa', qtdAulas: 1 }))); setMessage('Frequência salva.'); } catch (e) { setMessage(apiErrorMessage(e)); } };
  const saveGrades = async () => { if (!evaluationId) return; try { await Promise.all(selected.alunos.filter((x) => grades[x.id] !== undefined && grades[x.id] !== '').map((student) => api.post('/professor/notas', { idAvaliacao: Number(evaluationId), idMatricula: student.matriculaId, valorObtido: Number(grades[student.id]) }))); setMessage('Notas salvas.'); } catch (e) { setMessage(apiErrorMessage(e)); } };
  if (loading) return <div className="p-4">Carregando turmas...</div>;
  return <><div className="d-flex justify-content-between mb-4"><div><h2>Minhas turmas</h2><p className="text-muted">Dados acadêmicos do professor autenticado.</p></div>{selected && <button className="btn btn-outline-secondary" onClick={() => setSelected(null)}>Trocar turma</button>}</div>{message && <div className="alert alert-info">{message}</div>}
    {!selected ? <div className="row g-3">{classes.map((x) => <div className="col-md-6" key={x.id}><button className="card shadow-sm border-0 p-4 text-start w-100" onClick={() => choose(x)}><h5>{x.nomeTurma}</h5><p>{x.disciplinaNome}</p><small>{x.quantidadeInscritos} alunos · {x.horariosFormatados.join(' / ')}</small></button></div>)}</div> : <><h3>{selected.nomeTurma}</h3><p className="text-muted">{selected.disciplinaNome} · Sala {selected.sala}</p><div className="row g-3 mb-4">{[['Média atual', stats.average.toFixed(1)], ['Presença na chamada', `${stats.attendance.toFixed(0)}%`], ['Alunos abaixo de 6', stats.risk]].map(([label, value]) => <div className="col-md-4" key={label}><div className="card border-0 bg-light p-3 text-center"><h4>{value}</h4><small>{label}</small></div></div>)}</div>
      <div className="row g-4"><div className="col-lg-6"><div className="card shadow-sm border-0"><div className="card-header bg-white"><h5>Chamada</h5></div><div className="list-group list-group-flush">{selected.alunos.map((x) => <label className="list-group-item d-flex justify-content-between" key={x.id}><span>{x.nome}<small className="d-block text-muted">{x.ra}</small></span><input type="checkbox" className="form-check-input" checked={attendance[x.id] ?? true} onChange={(e) => setAttendance({ ...attendance, [x.id]: e.target.checked })} /></label>)}</div><div className="card-footer bg-white"><button className="btn btn-primary" onClick={saveAttendance}>Salvar frequência</button></div></div></div>
      <div className="col-lg-6"><div className="card shadow-sm border-0"><div className="card-header bg-white"><h5>Lançamento de notas</h5></div><div className="card-body"><select className="form-select mb-3" value={evaluationId} onChange={(e) => setEvaluationId(e.target.value)}><option value="">Selecione a avaliação</option>{selected.atividades.map((x) => <option key={x.id} value={x.id}>{x.nome}</option>)}</select>{selected.alunos.map((x) => <div className="input-group mb-2" key={x.id}><span className="input-group-text flex-grow-1">{x.nome}</span><input className="form-control" style={{ maxWidth: 100 }} type="number" min="0" max="10" step="0.1" value={grades[x.id] ?? ''} onChange={(e) => setGrades({ ...grades, [x.id]: e.target.value })} /></div>)}</div><div className="card-footer bg-white"><button className="btn btn-primary" disabled={!evaluationId} onClick={saveGrades}>Salvar notas</button></div></div></div></div></>}
  </>;
}
